main: main.cpp shape.cpp rectangle.cpp circle.cpp parallelepiped.cpp Cylinder.cpp rounded_rectangle.cpp
	g++ main.cpp shape.cpp rectangle.cpp circle.cpp parallelepiped.cpp Cylinder.cpp rounded_rectangle.cpp -o main -std=c++17 -g
run: main
	./main